// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Hub

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
lv_obj_t * ui_scrMain;
lv_obj_t * ui_pnlMain;
lv_obj_t * ui_btnHamburger;
lv_obj_t * ui_ctnrLeftRear;
lv_obj_t * ui_ctnrLeftRearGap;
lv_obj_t * ui_lblLeftRear;
lv_obj_t * ui_imgLeftRearWifi;
lv_obj_t * ui_ctnrRightRear;
lv_obj_t * ui_ctnrRightRearGap;
lv_obj_t * ui_lblRightRear;
lv_obj_t * ui_imgRightRearWifi;
lv_obj_t * ui_ctnrLeftFront;
lv_obj_t * ui_ctnrLeftFrontGap;
lv_obj_t * ui_lblLeftFront;
lv_obj_t * ui_imgLeftFrontWifi;
lv_obj_t * ui_ctnrRightFront;
lv_obj_t * ui_ctnrRightFrontGap;
lv_obj_t * ui_lblRightFront;
lv_obj_t * ui_imgRightFrontWifi;
lv_obj_t * ui_lblStatus1;
lv_obj_t * ui_lblStatus2;
lv_obj_t * ui_lblStatus3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrMain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrMain);
}
