// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Hub

#ifndef _HUB_UI_H
#define _HUB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_pnlMain;
extern lv_obj_t * ui_ctnrLeftRear;
extern lv_obj_t * ui_ctnrLeftRearGap;
extern lv_obj_t * ui_lblLeftRear;
extern lv_obj_t * ui_imgLeftRearWifi;
extern lv_obj_t * ui_ctnrRightRear;
extern lv_obj_t * ui_ctnrRightRearGap;
extern lv_obj_t * ui_lblRightRear;
extern lv_obj_t * ui_imgRightRearWifi;
extern lv_obj_t * ui_ctnrLeftFront;
extern lv_obj_t * ui_ctnrLeftFrontGap;
extern lv_obj_t * ui_lblLeftFront;
extern lv_obj_t * ui_imgLeftFrontWifi;
extern lv_obj_t * ui_ctnrRightFront;
extern lv_obj_t * ui_ctnrRightFrontGap;
extern lv_obj_t * ui_lblRightFront;
extern lv_obj_t * ui_imgRightFrontWifi;
extern lv_obj_t * ui_lblStatus1;
extern lv_obj_t * ui_lblStatus2;
extern lv_obj_t * ui_lblStatus3;
// CUSTOM VARIABLES

// SCREEN: ui_scrWheel
void ui_scrWheel_screen_init(void);
extern lv_obj_t * ui_scrWheel;
extern lv_obj_t * ui_pnlWheel;
extern lv_obj_t * ui_btnWheelBack;
extern lv_obj_t * ui_ddSelectedWheel;
extern lv_obj_t * ui_taCompressed;
extern lv_obj_t * ui_ctnrCompressionHeight;
extern lv_obj_t * ui_ctnrGap;
extern lv_obj_t * ui_lblGap;
extern lv_obj_t * ui_taExtended;
extern lv_obj_t * ui_chkSatellite1;
extern lv_obj_t * ui_lblSatellite1;
extern lv_obj_t * ui_chkSatellite2;
extern lv_obj_t * ui_lblSatellite2;
extern lv_obj_t * ui_chkSatellite3;
extern lv_obj_t * ui_lblSatellite3;
extern lv_obj_t * ui_chkSatellite4;
extern lv_obj_t * ui_lblSatellite4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
